### ISSUE TITLE
migrate from django to flask

### ISSUE THREAD

**Issue by wsoule** [shoberg44/my_project#5]
https://www.freecodecamp.org/news/how-to-build-a-web-application-using-flask-and-deploy-it-to-the-cloud-3551c985e492/

@Amecara

Delete the current repo at "my_project" and start a flask application with the tutorial above.

**Comment by suiseiressya** [comment]
just done it but edited a bit since the tutorial is deprecated 
https://imagine-441904.uc.r.appspot.com/about
https://imagine-441904.uc.r.appspot.com/
